### ISSUE TITLE
无法创建 EconomyService 服务

### ISSUE THREAD

**Issue by MrXiaoM** [cssxsh/mirai-economy-core#8]
```
2022-12-03 20:47:41 E/mirai-economy-core: java.util.ServiceConfigurationError: 无法创建 EconomyService 服务
java.util.ServiceConfigurationError: 无法创建 EconomyService 服务
	at mirai-economy-core-1.0.4.mirai2.jar//xyz.cssxsh.mirai.economy.service.IEconomyService$Factory.create(EconomyService.kt:98)
	at mirai-economy-core-1.0.4.mirai2.jar//xyz.cssxsh.mirai.economy.EconomyService.<init>(EconomyService.kt:21)
	at mirai-economy-core-1.0.4.mirai2.jar//xyz.cssxsh.mirai.economy.EconomyService.<clinit>(EconomyService.kt)
	at mirai-economy-core-1.0.4.mirai2.jar//xyz.cssxsh.mirai.economy.console.MiraiEconomyCorePlugin.onEnable(MiraiEconomyCorePlugin.kt:43)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:278)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:178)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:235)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
```
```
Running MiraiConsole v2.12.3, built on 2022-09-11 21:02:46.
Frontend Terminal: version 2.12.3, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: mirai-hibernate-plugin v2.5.0, mirai-economy-core(disabled) v1.0.4, MiraiDailySign(disabled) v0.1.0
```

**Comment by MrXiaoM** [comment]
在 2.13.0-RC2、2.13.0-RC、2.13.0-M1 正常，或许应该兼容下 2.11+ 或者标注一下最低版本？
